services:
  receiver:
    build:
      context: ./receiver
    ports:
      - "5001:5001"
    container_name: receiver

  scanner1:
    build:
      context: ./scanner
    ports:
      - "22:22"
      - "80:80"
      - "443:443"
    container_name: scanner1
    depends_on:
      - receiver

  scanner2:
    build:
      context: ./scanner
    ports:
      - "3306:3306"
      - "5432:5432"
      - "8080:8080"
    container_name: scanner2
    depends_on:
      - receiver